# inventory/group_vars/DC1_L3_LEAVES.yml
type: l3leaf

l3leaf:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.255.1.0/24
    vtep_loopback_ipv4_pool: 10.255.2.0/24
    uplink_interfaces: [Ethernet1, Ethernet2]
    uplink_switches: [dc1-spine1, dc1-spine2]
    uplink_ipv4_pool: 10.255.255.0/24
    mlag_interfaces: [Ethernet3, Ethernet4]
    mlag_peer_ipv4_pool: 10.255.254.0/24
    mlag_peer_l3_ipv4_pool: 10.255.253.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
  node_groups:
    - group: DC1_LEAF1
      bgp_as: 65101
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.100.100.101/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.100.100.102/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: DC1_LEAF2
      bgp_as: 65102
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 172.100.100.103/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 172.100.100.104/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
